### ISSUE TITLE
Function Vector Range Exception 

### ISSUE THREAD

**Issue by mistercherryy** [Adjuvo/SenseGlove-API#10]
Hello @MaxLammers ,

like in the pictures below i receive runtime library error because of CalculateFingerTips(handprofile) function in SenseGloveCpp.cpp from examples file. The functions triggers a breakpoint and throws an exception. Getting sensor data or serialization works fine but due to this error i cannot get the fingertip positions. Do you have any suggestions to solve this problem? 

Regards
![error together](https://user-images.githubusercontent.com/46500249/125265507-32b50d80-e305-11eb-9cbb-d8a776dd4232.JPG)
![error2](https://user-images.githubusercontent.com/46500249/125265676-5c6e3480-e305-11eb-8040-c0f5254cdc30.JPG)

**Comment by MaxLammers** [comment]
Dear @mistercherryy, thanks for bringing this to our attention.

Found a bug in the back-end where fingerThimbleOffsets (used to calculate fingertip location) were lost, resetting to a vector with length 0, which was causing the error. Fixed in the [latest update](https://github.com/Adjuvo/SenseGlove-API/commit/21f284f6b58976253b23b550e189b202055faa8a).
